#! /bin/sh

# SCRIPT: maninstall
# Installs the manpages for mod_auth_ibmdb2
# Usage: maninstall [/path/to/manpages]

if [ -n "$1" ]
then
	path=$1
fi

if [ -d /usr/share/man ]
then
	path=/usr/share/man
else
	if [ -n "$1" ]
	then
        	path=$1
	else
		echo ""
		echo "Ooops, cannot find a manpages directory!"
		echo "Please specify the manpages directory - Do NOT specify the section!"
		echo ""
		echo "maninstall /path/to/manpages"
		echo ""
		exit
	fi
fi

if [ ! -d "$path" ]
then
        echo ""
        echo "Sorry, directory $path does not exist!"
        echo ""
        exit
fi

if [ -d $path/man8 ]
then
	path=$path/man8
else
	echo "section man8 does not exist ... creating."
	path=$path/man8
	mkdir $path
	echo "directory $path created."
fi

if [ "`uname`" = "Linux" ]
then
	gzip ./man8/*
	cp ./man8/* $path
	gunzip ./man8/*
else
	cp ./man8/* $path
fi

echo "Manpages installed in directory $path"

exit
