#! /bin/sh

# $Id$

# SCRIPT: makemod
# Builds the mod_authnz_ibmdb2 module and moves it to the modules directory
# Usage: makemod

# Set DB2PATH to where DB2 will be accessed.
# Set APXS to the path that points to your apxs binary

# Path settings

DB2PATH=/home/db2inst1/sqllib
APXS=/usr/local/apache/bin/apxs

#
# clean up left-overs from previous build:
#
if [ -d .libs ]
then
	rm -rf .libs
fi

for x in mod_authnz_ibmdb2.la mod_authnz_ibmdb2.lo mod_authnz_ibmdb2.o mod_authnz_ibmdb2.slo mod_authnz_ibmdb2.so
do
	if [ -f $x ]
	then
		rm $x
	fi
done

# Set extra flags for the linker

if [ "`uname`" = "AIX" ]
then
	EXTRA_LFLAG="-Wl,-G,-blibpath:$DB2PATH/lib"
else
	EXTRA_LFLAG="-Wl,-rpath,$DB2PATH/lib"
fi

# Build the module

$APXS -c -I$DB2PATH/include -L$DB2PATH/lib $EXTRA_LFLAG -ldb2 mod_authnz_ibmdb2.c

# Moving the module to the apropriate directory

$APXS -i mod_authnz_ibmdb2.la
