.TH md5 "8" "June 2004" "md5" "DB2 User Defined Function"
.SH NAME
md5 \- DB2 UDF for encrypting passwords
.SH SYNOPSIS
>>-MD5--(--expression--)---------------------------------------><
.SH DESCRIPTION
MD5 hash. The md5 function is compatible to the PHP md5 function.
.PP
The argument can be a character string that is either a CHAR or VARCHAR not exceeding 120 bytes.
.PP
The result of the function is VARCHAR(32). The result can be null; if the argument is null, the result is the null value.
.SH EXAMPLES
1)
.br
Inserting the user \fItest\fR and the md5 hash of the clear text \fItestpwd\fR to the table \fIusers\fR.
.PP
.nf
INSERT INTO USERS (username, password) 
  VALUES ('test', md5('testpwd'))
.fi
.PP
2)
.br
.nf
SELECT md5( 'testpwd' ) FROM SYSIBM.SYSDUMMY1

1
--------------------------------
342df5b036b2f28184536820af6d1caf

  1 record(s) selected.
.fi
.SH AUTHOR
Written by Helmut K. C. Tessarek.
.SH "BUGS"
Hopefully none :-) But if you find one, please report it at:
http://sourceforge.net/tracker/?func=add&group_id=103064&atid=633717
.SH "WEB SITE"
http://mod-auth-ibmdb2.sourceforge.net/
